### ISSUE TITLE
*** [.pio\build\stm32_ret6\firmware.elf] Error 1

### ISSUE THREAD

**Issue by GriffelG** [weedo3d/MiniDeltaV2firmware#2]
Everytime I try to compile the firmware to a .bin file I get this error code:

c:/.platformio/packages/toolchain-gccarmnoneeabi@1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld.exe: cannot open linker script file C:/Users/Username/Downloads/MiniDeltaV2firmware-main/MiniDeltaV2firmware-main/buildroot/share/PlatformIO/ldscripts/WEEDOR83.ld: Invalid argument
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\stm32_ret6\firmware.elf] Error 1

**Comment by weedo3d** [comment]
The compiler prompts that the file \buildroot\share\PlatformIO\ldscripts\WEEDOR83.ld was not found.
Please check if the file exists. If not please download it again from github. 
https://github.com/weedo3d/MiniDeltaV2firmware/blob/main/buildroot/share/PlatformIO/ldscripts/WEEDOR83.ld
