### ISSUE TITLE
What is the use case for MiniDeltaV2_V1.1.5_Official_Release.wfm?

### ISSUE THREAD

**Issue by ricardodeazambuja** [weedo3d/MiniDeltaV2firmware#3]
I wonder if MiniDeltaV2_V1.1.5_Official_Release.wfm can be flashed as [the original motor firmware](http://mpminideltav2.com/doku.php?id=firmware:how_to_update_firmware) using the sd card. Is it the case?

**Comment by weedo3d** [comment]
Yes, firmware in .wfm format can be updated from sd card.

**Comment by weedo3d** [comment]
After copying the .wfm file to the sd card, you need to change the filename to flash.wfm

**Comment by ricardodeazambuja** [comment]
Thanks. Is this better than [the official V1.2.0](http://mpminideltav2.com/doku.php?id=firmware:mp_mini_delta_v2)?

**Comment by weedo3d** [comment]
V1.2.0 is the latest firmware. This week I will release the V1.2.0 open source code.

**Comment by ricardodeazambuja** [comment]
Today I decided to try the V1.2.0, but it stops at "Cannot mount the filesystem or find file with flash", but it had found the file because it was showing the version. Any suggestions? 
The steps I took were: I downloaded [the file from this repo](https://github.com/weedo3d/MiniDeltaV2firmware/blob/main/Release/V1.2.0/MiniDeltaV2_V1.2.0_Official_Release.wfm), changed the name to "flash.wfm", copied to the sdcard root, inserted the sdcard, went to settings / update... and that's it :)

**Comment by ricardodeazambuja** [comment]
Ok, I used one of my sdcards instead of the one that came with the printer and it worked :D
